"""empty message

Revision ID: 281d73854272
Revises: 803af7a9c49d
Create Date: 2020-06-15 02:18:50.563742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281d73854272'
down_revision = '803af7a9c49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carpool', sa.Column('car_year', sa.Integer(), nullable=True))
    op.drop_constraint('carpool_car_make_key', 'carpool', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('carpool_car_make_key', 'carpool', ['car_make'])
    op.drop_column('carpool', 'car_year')
    # ### end Alembic commands ###
