"""empty message

Revision ID: 2a9c15d133ee
Revises: 39f84c4954cb
Create Date: 2021-09-20 23:37:21.485822

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2a9c15d133ee'
down_revision = '39f84c4954cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('qr_url', sqlalchemy_utils.types.url.URLType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'qr_url')
    # ### end Alembic commands ###
