"""empty message

Revision ID: 346eafd3764f
Revises: ca5b20ab8bde
Create Date: 2021-07-12 12:56:50.966422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '346eafd3764f'
down_revision = 'ca5b20ab8bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('passengers_trip_id_key', 'passengers', type_='unique')
    op.create_unique_constraint(None, 'passengers', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passengers', type_='unique')
    op.create_unique_constraint('passengers_trip_id_key', 'passengers', ['trip_id'])
    # ### end Alembic commands ###
