"""empty message

Revision ID: 35273b9be8be
Revises: 281d73854272
Create Date: 2020-06-18 22:51:23.679349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35273b9be8be'
down_revision = '281d73854272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slugs', sa.Column('slug_id', sa.Integer(), nullable=False))
    op.drop_column('slugs', 'carpool_id')
    op.alter_column('users', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('slugs', sa.Column('carpool_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('slugs', 'slug_id')
    # ### end Alembic commands ###
