"""empty message

Revision ID: 39f84c4954cb
Revises: db3469c9fca1
Create Date: 2021-07-14 20:01:03.674013

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils 


# revision identifiers, used by Alembic.
revision = '39f84c4954cb'
down_revision = 'db3469c9fca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_photo', sqlalchemy_utils.types.url.URLType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_photo')
    # ### end Alembic commands ###
