"""empty message

Revision ID: 4c213713c091
Revises: e6b0397575d6
Create Date: 2021-06-24 20:41:18.223686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c213713c091'
down_revision = 'e6b0397575d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dropoff_locations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('dropoff_locations', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_unique_constraint(None, 'passengers', ['trip_id'])
    op.add_column('pickup_locations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('pickup_locations', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pickup_locations', 'longitude')
    op.drop_column('pickup_locations', 'latitude')
    op.drop_constraint(None, 'passengers', type_='unique')
    op.drop_column('dropoff_locations', 'longitude')
    op.drop_column('dropoff_locations', 'latitude')
    # ### end Alembic commands ###
