"""empty message

Revision ID: 803af7a9c49d
Revises: 
Create Date: 2020-06-15 02:12:21.370808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803af7a9c49d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carpool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_make', sa.Integer(), nullable=True),
    sa.Column('owner_email', sa.String(length=18), nullable=True),
    sa.ForeignKeyConstraint(['owner_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_make')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carpool')
    # ### end Alembic commands ###
