"""empty message

Revision ID: 82372ab47886
Revises: 9bc499422a89
Create Date: 2021-07-12 18:37:22.554603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82372ab47886'
down_revision = '9bc499422a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_history', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_history', 'active')
    # ### end Alembic commands ###
