"""empty message

Revision ID: 88176541e364
Revises: 4bd41ad64899
Create Date: 2020-07-10 23:45:30.625493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88176541e364'
down_revision = '4bd41ad64899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qr_string', sa.String(length=18), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_ended', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carpool',
    sa.Column('cars_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cars_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('cars_id', 'users_id')
    )
    op.drop_table('slugs')
    op.add_column('users', sa.Column('is_driver', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_driver')
    op.create_table('slugs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('slug_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_ended', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='carpool_pkey')
    )
    op.drop_table('carpool')
    op.drop_table('trips')
    op.drop_table('cars')
    # ### end Alembic commands ###
