"""empty message

Revision ID: 9bc499422a89
Revises: 71d39db0a35b
Create Date: 2021-07-12 18:19:01.455129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bc499422a89'
down_revision = '71d39db0a35b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('passenger_history_trip_id_fkey', 'passenger_history', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('passenger_history_trip_id_fkey', 'passenger_history', 'trip_history', ['trip_id'], ['id'])
    # ### end Alembic commands ###
