"""empty message

Revision ID: ca5b20ab8bde
Revises: 4c213713c091
Create Date: 2021-06-29 15:19:28.896182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5b20ab8bde'
down_revision = '4c213713c091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'active')
    # ### end Alembic commands ###
