"""empty message

Revision ID: ca74d935a5e9
Revises: bd01a329748f
Create Date: 2020-07-31 14:01:31.655621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca74d935a5e9'
down_revision = 'bd01a329748f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('car_make', sa.String(length=18), nullable=False))
    op.add_column('cars', sa.Column('car_year', sa.Integer(), nullable=False))
    op.add_column('cars', sa.Column('ezpass_tag', sa.String(length=18), nullable=False))
    op.add_column('cars', sa.Column('license_plate', sa.String(length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'license_plate')
    op.drop_column('cars', 'ezpass_tag')
    op.drop_column('cars', 'car_year')
    op.drop_column('cars', 'car_make')
    # ### end Alembic commands ###
