"""empty message

Revision ID: db3469c9fca1
Revises: fb39d6d84f99
Create Date: 2021-07-12 19:11:52.985718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3469c9fca1'
down_revision = 'fb39d6d84f99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trip_history', ['trip_id'])
    op.create_foreign_key(None, 'passenger_history', 'trip_history', ['trip_id'], ['trip_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip_history', type_='unique')
    op.drop_constraint(None, 'passenger_history', type_='foreignkey')
    # ### end Alembic commands ###
