"""empty message

Revision ID: e069891b07c5
Revises: e829f1a92569
Create Date: 2021-06-16 20:43:20.019718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e069891b07c5'
down_revision = 'e829f1a92569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'trips', ['car_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trips', type_='unique')
    # ### end Alembic commands ###
