"""empty message

Revision ID: e21a2a91c268
Revises: 3586505f3366
Create Date: 2020-07-13 23:59:44.836689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21a2a91c268'
down_revision = '3586505f3366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'cars', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.drop_column('cars', 'owner_id')
    # ### end Alembic commands ###
