"""empty message

Revision ID: e6b0397575d6
Revises: 4a6c317ffaac
Create Date: 2021-06-18 15:12:46.762902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b0397575d6'
down_revision = '4a6c317ffaac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('session_id', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'session_id')
    # ### end Alembic commands ###
