"""empty message

Revision ID: fb39d6d84f99
Revises: 82372ab47886
Create Date: 2021-07-12 18:51:47.199416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb39d6d84f99'
down_revision = '82372ab47886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip_history', sa.Column('trip_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip_history', 'trip_id')
    # ### end Alembic commands ###
